name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t auth6one .
          docker tag auth6one:latest ${{ secrets.DOCKERHUB_USERNAME }}/auth6one:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/auth6one:latest
